name: Build Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.33
        env:
          APP_VERSION: $(basename ${GITHUB_REF})
          VERSION: ${{github.ref_name}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.19"
          project_path: "."
          ldflags: -X "github.com/sideninja/flow-cli/flow.semver=$(VERSION)" -X "github.com/sideninja/flow-cli/flow.boo=\"boo\""