name: Publish Release

on: workflow_dispatch
jobs:
  homebrew:
    if: "!github.event.release.prerelease"
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: echo "HELLO"