name: Publish Release

on:
  release:
    types: [published]

jobs:
  homebrew:
    if: github.event_name == 'release' && github.event.action == 'published' # skip for pre-release
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: echo "HELLO"